
# Because we want to easily inspect the

name: Post Diff Comment

on:
  # Note! you can't safely use "pull_request_target" here
  # This workflow is mostly useful for "internal PRs"
  # External PRs won't be able to post a PR comment
  # See https://github.com/preactjs/compressed-size-action/issues/54
  # See https://securitylab.github.com/research/github-actions-preventing-pwn-requests
  pull_request:
    branches:
      - master

jobs:
  post-diff-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install
      - name: Build master/branch dists
        id: dists
        run: |
          yarn workspace infima build
          mv packages/core/dist packages/core/dist-branch
          git checkout master
          yarn workspace infima build
          OUTPUT=$(git diff --no-index --color packages/core/dist/css/default/default.css packages/core/dist-branch/css/default/default.css | cat)
          echo "::set-output name=result::$OUTPUT"

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: post-diff-comment
          message: |
            ```
            Dist CSS diff:

            ${{ steps.dists.outputs.result }}
            ```
